# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: control_alumnos
  username: root
  password: admin
  host: localhost
test:
  adapter: mysql2
  database: control_alumnos
  username: root
  password: admin
  host: localhost
production:
  adapter: mysql2
  database: control_alumnos
  username: root
  password: admin
  host: localhost
